### ISSUE TITLE
Also do bower.json?

### ISSUE THREAD

**Issue by RobLoach** [madeofpeople/metalsmith-packagejson#3]

**Comment by julkue** [comment]
@RobLoach In general, there is no need for a plugin like this. Just use the built in method `metadata()` like so:

``` javascript
Metalsmith(__dirname)
    .metadata(JSON.parse(fs.readFileSync("bower.json", "utf8")))
```

or if you prefer to have the key "bower":

``` javascript
Metalsmith(__dirname)
    .metadata(() => {
        return {"bower": JSON.parse(fs.readFileSync("bower.json", "utf8"))};
    }())
```

**Comment by RobLoach** [comment]
@julmot You are suggesting adding in some code in the configuration that would load `bower.json` into the metadata plugin. The aim of this is to work without needing to add any more code.

It does bring up a neat idea of just having `metalsmith-packagejson` invoke `metadata()` in that way, actively performing the task you suggested..

**Comment by julkue** [comment]
@RobLoach I agree with you. However, the difference is that I don't need to check for updates of this plugin and I can use it for any JSON file, not just for "package.json" (e.g. bower.json). For example:

``` javascript
.metadata({ // allow accessing metadata via handlebars
    "defaults": JSON.parse(fs.readFileSync(metadataConfig, "utf8")),
    "pkg": JSON.parse(fs.readFileSync(packageConfig, "utf8"))
})
```

And this tiny bit of code should not be overtaxing.

**Comment by thiagodemellobueno** [comment]
@julmot, you are generally correct, this plugin is mostly meant for metalsmith.json use cases where that kind of inline JS isn't possible. 

That said our project should probably ove to good ol' index.js instead of metalsmith.json (thoughts @RobLoach )

**Comment by thiagodemellobueno** [comment]
@RobLoach as far as adding bower.json, I can see some use, but maybe let's experience the need before working on that feature.
