### ISSUE TITLE
publish current state to npm

### ISSUE THREAD

**Issue by rodneyrehm** [madeofpeople/metalsmith-packagejson#4]
The current version of this plugin on npm is 1.0.1 and still contains the defunct module [fs](https://www.npmjs.com/package/fs), which seems to have been fixed in dbccc6d. Is it possible to publish the current state of master (assuming tests are passing, etc.) to npm?

**Comment by thiagodemellobueno** [comment]
Hello, absolutely.
Thanks for the heads up.

**Comment by thiagodemellobueno** [comment]
@rodneyrehm this has been updated.
